UPDATEHUB_RUNTIME_UHQA = "/data/updatehub"

UPDATEHUB_RUNTIME_uh-qemu-armv5e = "${UPDATEHUB_RUNTIME_UHQA}"
UPDATEHUB_RUNTIME_uh-qemu-i386   = "${UPDATEHUB_RUNTIME_UHQA}"
UPDATEHUB_RUNTIME_uh-qemu-x86-64 = "${UPDATEHUB_RUNTIME_UHQA}"
